# Generated by Django 6.1.1 on 2026-09-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(choices=[('lipa_pole_pole', 'Lipa Pole Pole'), ('cash', 'Cash'), ('mpesa', 'Mpesa STK Push')], default='cash', max_length=30),
        ),
    ]
